### PR TITLE
Add puppet tests from praekelt/puppet and run with Travis

### PR DESCRIPTION
**Pull request by JayH5**

### CODE REVIEW

**Comment by JayH5** [comment]
@jerith: The Trusty VM I just started reports Puppet 3.4.3 :/

Puppet 3.4.3 seems to spew tonnes of debug output with `puppet-catalog-test` but does work. Maybe we should update puppet on the VM?

**Comment by jerith** [comment]
:+1:

We're just using puppet for provisioning, so I don't think we really need a newer version. (It might be worth it if it speeds stuff up, though.)

**Comment by JayH5** [comment]
@jerith: Changed some things - ready for re-review.
- The paths in the puppet scripts now expect that the scripts are being run from the `puppet` directory.
- Added a Gemfile and got Travis to use Bundler (after some trying) so that it caches gems.

**Comment by jerith** [comment]
Do we want `Gemfile.lock` in there?

**Comment by JayH5** [comment]
@jerith: Apparently, if you're not packaging a gem then you should have it in your repo: http://stackoverflow.com/a/4151540, also says to `git add Gemfile Gemfile.lock` on http://bundler.io

Does seem a bit weird to me too :/

**Comment by jerith** [comment]
Cool. :+1:

**Pull request merged**
