### PR TITLE
Having both a domain and location label for an app results in invalid nginx config

### PR DESCRIPTION
**Pull request by JayH5**
It's useful to sometimes have both a `domain` and `location` label for an app so that the app's internal API can be used as well as its web interface.

Including both labels results in the app being present in two nginx config files. Nginx does not like when there are multiple `upstream` declarations with the same name and will fail to load the config.

### CODE REVIEW

**Comment by JayH5** [comment]
@smn: Ready for review.

**Comment by smn** [comment]
Interesting, does simply moving it to a separate config file make nginx happy or what am I missing here?

**Comment by JayH5** [comment]
`upstream`s are in a "global" namespace. If two are specified with the same name then there's a problem. If the same `upstream` is in both the "websites" and "services" then this happens.

**Comment by smn** [comment]
:+1:

**Pull request merged**
